name: Release

on:
  push:
    branches:
      - main
permissions:
  contents: write
  packages: write
  pull-requests: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "19"

      - name: Install multi-semantic-release
        run: |
          npm install

      - name: Run semantic release
        run: |
          npx multi-semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}